CREATE TABLE PESSOAS(
IDPESSOA INTEGER PRIMARY KEY NOT NULL,
NOME VARCHAR(100) NOT NULL DEFAULT '',
CPF INTEGER NOT NULL,
RG INTEGER NOT NULL,
SEXO CHAR(1) NOT NULL DEFAULT '',
DATANASCIMENTO DATE NOT NULL,
TELEFONE INTEGER NOT NULL,
ENDERECO VARCHAR(100) NOT NULL DEFAULT '',
DATACADASTRO DATE NOT NULL
);

--SELECT * FROM PESSOAS
--INSERT INTO PESSOAS (IDPESSOA, NOME, CPF, RG, SEXO, DATANASCIMENTO, TELEFONE, ENDERECO, DATACADASTRO) VALUES (1, 'PEDRO', 045882419, 86155524, 'M', '19841202', 35362666, 'RUA JEQUETIBA', '20161005')


CREATE TABLE ESTOQUE(
IDESTOQUE INTEGER PRIMARY KEY NOT NULL,
IDLIVRO INTEGER NOT NULL
);

CREATE TABLE EDITORA(
IDEDITORA INTEGER PRIMARY KEY NOT NULL,
NOME VARCHAR(100) NOT NULL DEFAULT ''
);

CREATE TABLE AUTOR(
IDAUTOR INTEGER PRIMARY KEY NOT NULL,
NOME VARCHAR(100) NOT NULL DEFAULT ''
);

CREATE TABLE GENEROS(
IDGENERO INTEGER PRIMARY KEY NOT NULL,
GENERO VARCHAR(100) NOT NULL DEFAULT ''
);

CREATE TABLE LIVROS(
IDLIVRO INTEGER PRIMARY KEY NOT NULL,
IDGENERO INTEGER NOT NULL,
IDAUTOR INTEGER NOT NULL,
IDEDITORA INTEGER NOT NULL,
TITULO VARCHAR(100) NOT NULL DEFAULT '',
CONSTRAINT LIVROS_IDGENERO FOREIGN KEY (IDGENERO) REFERENCES GENEROS (IDGENERO),
CONSTRAINT LIVROS_IDAUTOR FOREIGN KEY (IDAUTOR) REFERENCES AUTOR (IDAUTOR),
CONSTRAINT LIVROS_IDEDITORA FOREIGN KEY (IDEDITORA) REFERENCES EDITORA (IDEDITORA)
);


CREATE TABLE USUARIOS(
IDUSUARIO INTEGER PRIMARY KEY NOT NULL,
IDPESSOA INTEGER NOT NULL,
CONSTRAINT FK_USUARIOS_IDPESSOA FOREIGN KEY (IDPESSOA) REFERENCES PESSOAS (IDPESSOA)
);

CREATE TABLE EMPRESTIMOS(
IDEMPRESTIMO INTEGER PRIMARY KEY NOT NULL,
IDUSUARIO INTEGER NOT NULL,
IDLIVRO INTEGER NOT NULL,
PREVISAO_ENTREGA DATE NOT NULL,
DATA_DEVOLUCAO DATE NOT NULL,
QTDEMPRESTIMO INTEGER NOT NULL,
CONSTRAINT EMPRESTIMOS_IDUSUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS (IDUSUARIO),
CONSTRAINT EMPRESTIMOS_IDLIVRO FOREIGN KEY (IDLIVRO) REFERENCES LIVROS (IDLIVRO)
);

CREATE TABLE FUNCIONARIOS(
IDFUNCIONARIO SERIAL PRIMARY KEY NOT NULL,
IDPESSOA INTEGER NOT NULL,
GARGO VARCHAR(50) NOT NULL DEFAULT '',
SALARIO FLOAT NOT NULL,
CONSTRAINT FK_FUNCIONARIO_IDPESSOA FOREIGN KEY (IDPESSOA) REFERENCES PESSOAS (IDPESSOA)
);
--SELECT * FROM FUNCIONARIOS
--INSERT INTO FUNCIONARIOS (IDFUNCIONARIO, IDPESSOA, GARGO, SALARIO) VALUES (1, 1, 'ADMINISTRADOR', 1800)

CREATE TABLE LOGIN(
IDLOGIN SERIAL PRIMARY KEY NOT NULL,
IDFUNCIONARIO SERIAL NOT NULL,
DESCRICAO VARCHAR(50) NOT NULL,
SENHA VARCHAR(8) NOT NULL,
CONSTRAINT LOGIN_IDFUNCIONARIO FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIOS (IDFUNCIONARIO)
);

--INSERT INTO LOGIN (IDLOGIN, IDFUNCIONARIO, DESCRICAO, SENHA) VALUES (1, 1, 'ADMIN', '123456')
--SELECT * FROM LOGIN
