CREATE TABLE PESSOA(
IDPESSOA INTEGER PRIMARY KEY NOT NULL,
NOME VARCHAR(100) NOT NULL,
CPF INTEGER NOT NULL,
RG INTEGER NOT NULL,
SEXO CHAR(1) NOT NULL,
DATANASCIMENTO DATE NOT NULL,
TELEFONE INTEGER NOT NULL,
ENDERECO VARCHAR(100) NOT NULL,
DATACADASTRO DATE NOT NULL
);

CREATE TABLE FUNCIONARIOS(
IDFUNCIONARIO SERIAL PRIMARY KEY NOT NULL,
IDPESSOA INTEGER NOT NULL,
SALARIO FLOAT NOT NULL,
CONSTRAINTS FK_FUNCIONARIO_IDPESSOA FOREIGN KEY (IDPESSOA) REFERENCES PESSOA IDPESSOA
);



CREATE TABLE USUARIOS(
IDUSUARIO INTEGER PRIMARY KEY NOT NULL,
IDPESSOA INTEGER NOT NULL,
CONSTRAINTS FK_USUARIO_IDPESSOA FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS IDUSUARIO
);

CREATE TABLE LOGIN(
IDLOGIN SERIAL PRIMARY KEY NOT NULL,
IDFUNCIONARIO SERIAL NOT NULL,
NOME VARCHAR(50) NOT NULL,
SENHA VARCHAR(8) NOT NULL,
CONSTRAINT LOGIN_IDFUNCIONARIO FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIOS IDFUNCIONARIO
);

CREATE TABLE EMPRESTIMOS(
IDEMPRESTIMO INTEGER PRIMARY KEY NOT NULL,
IDUSUARIO INTEGER NOT NULL,
IDLIVRO INTEGER NOT NULL,
PREVISAO_ENTREGA DATE NOT NULL,
DATA_DEVOLUCAO DATE NOT NULL,
QTDEMPRESTIMO INTEGER NOT NULL,
CONSTRAINTS EMPRESTIMOS_IDUSUARIO FOREIGN KEY IDUSUARIO REFERENCES USUARIOS IDUSUARIO,
CONSTRAINTS EMPRESTIMOS_IDLIVRO FOREIGN KEY IDLIVRO REFERENCES LIVROS IDLIVRO
);

CREATE TABLE LIVROS(
IDLIVRO INTEGER PRIMARY KEY NOT NULL,
IDGENERO INTEGER NOT NULL,
IDAUTOR INTEGER NOT NULL,
IDEDITORA INTEGER NOT NULL,
CONSTRAINTS LIVROS_IDGENERO FOREIGN KEY IDGENERO REFERENCES GENEROS IDGENERO,
CONSTRAINTS LIVROS_IDAUTOR FOREIGN KEY IDAUTOR REFERENCES AUTOR IDAUTOR,
CONSTRAINTS LIVROS_IDEDITORA FOREIGN KEY IDEDITORA REFERENCES EDITORA IDEDITORA
);

CREATE TABLE GENEROS(
IDGENERO INTEGER PRIMARY KEY NOT NULL,
GENERO VARCHAR(100) NOT NULL
);

CREATE TABLE AUTOR(
IDAUTOR INTEGER PRIMARY KEY NOT NULL,
NOME VARCHAR(100) NOT NULL
);

CREATE TABLE EDITORA(
IDEDITORA INTEGER PRIMARY KEY NOT NULL,
NOME VARCHAR(100) NOT NULL
);

CREATE TABLE ESTOQUE(
IDESTOQUE INTEGER PRIMARY KEY NOT NULL,
IDLIVRO INTEGER NOT NULL
);

